name: qac
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+7

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.5
  card_slider: ^1.0.5
  webview_flutter: ^3.0.4
  get: ^4.6.5
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  get_storage: ^2.1.1
  animated_splash_screen: ^1.3.0
  url_launcher: ^6.1.11
  onesignal_flutter: ^3.5.0
  change_app_package_name: ^1.1.0
  font_awesome_flutter: ^10.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.»
  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/delivered.jpg
    - assets/images/efawateer.png
    - assets/images/hand.jpg
    - assets/images/jouhd_logo.png
    - assets/images/logo.png
    - assets/images/part.jpg
    - assets/images/qac_logo.png
    - assets/images/winners.jpg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
