/// Generated by AssetsRefGenerator - DO NOT MODIFY BY HAND
class Res {
  static const String audio = "assets/images/audio.png";
  static const String back_2 = "assets/images/back-2.png";
  static const String commities = "assets/images/commities.png";
  static const String infobook = "assets/images/infobook.png";
  static const String leaf = "assets/images/leaf.png";
  static const String login = "assets/images/login.svg";
  static const String mision = "assets/images/mision.png";
  static const String news = "assets/images/news.png";
  static const String printable = "assets/images/printable.png";
  static const String qac_home2 = "assets/images/qac-home2.png";
  static const String register = "assets/images/register.svg";
  static const String splash_2 = "assets/images/splash-2.png";
  static const String utils = "assets/images/utils.png";
  static const String video = "assets/images/video.png";
  static const String vision = "assets/images/vision.png";
}
